# Generated by Django 4.2 on 2024-10-08 19:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name="player",
            name="age",
        ),
        migrations.RemoveField(
            model_name="player",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="player",
            name="team",
        ),
        migrations.AddField(
            model_name="player",
            name="bio",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="email",
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="phone",
            field=models.CharField(default="", max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="sport",
            field=models.CharField(default="", max_length=50),
            preserve_default=False,
        ),
    ]
