# Generated by Django 4.2 on 2024-10-10 07:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0003_contact_submitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="player",
            name="gender",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        # migrations.AddField(
        #     model_name="player",
        #     name="team",
        #     field=models.ForeignKey(
        #         blank=True,
        #         null=True,
        #         on_delete=django.db.models.deletion.CASCADE,
        #         to="sports.team",
        #     ),
        # ),
        migrations.AlterField(
            model_name="contact",
            name="submitted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
