# Generated by Django 4.2 on 2024-10-10 07:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0004_player_age_player_position_player_team_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="submitted_at",
        ),
    ]
