# Generated by Django 4.2 on 2024-10-11 15:16

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("sports", "0005_remove_contact_submitted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="submitted_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="player",
            name="age",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="gender",
            field=models.CharField(default="Not Specified", max_length=50),
        ),
    ]
